development:
  adapter: postgresql
  database: r2pp_development
  host: localhost

test:
  adapter: postgresql
  database: r2pp_test
  host: localhost

production:
  adapter: postgresql
  database: r2pp_production
  host: localhost
